### ISSUE TITLE
Fix memory leaking issues

### ISSUE THREAD

**Issue by rinrincodes** [Mica-Technologies/Minecraft-Forge-Launcher#43]
There seems to be a huge memory leak that causes random lag spikes with Minecraft on both online and local worlds when it is launched from the launcher. I'm not sure where this is all coming from.

**Comment by rinrincodes** [comment]
Log from the launcher can't be uploaded at this time as the launcher logger is currently broken as mentioned in #42. After that is fixed I'll post a log here showing what might be going wrong with Minecraft having a lot of memory leaks on both the server and client.

**Comment by hawka97** [comment]
@rinrincodes I've rebuilt and republished Release Candidate 2. Try that, it should be fixed. If it is, please close this issue.

**Comment by rinrincodes** [comment]
Memory leak is somewhat fixed but is still present in the launcher. Leaving this issue open till it gets fixed.

**Comment by rinrincodes** [comment]
No more tweaking to it for memory leaks apparently can't be done. Closing this now.
